 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/sensocms:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/sensocms:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'sensocms'
   - '--image'
   - 'gcr.io/$PROJECT_ID/sensocms:$COMMIT_SHA'
   - '--region'
   - 'europe-west1'
   - '--platform'
   - 'managed'
   - '--add-cloudsql-instances'
   - 'sensocms'
   - '--update-env-vars'
   - 'INSTANCE_CONNECTION_NAME=sensotest-278921:europe-west3:sensocms'
   - '--port'
   - '80'
 images:
 - 'gcr.io/$PROJECT_ID/sensocms:$COMMIT_SHA'
